### ISSUE TITLE
Error launching lsnes

### ISSUE THREAD

**Issue by Yupppi** [bentley/lsnes#1]
I get following warning on windows 7 with installer and non-installer versions from TASvideos. Any help? I tried installing bizhawk pre-requisites for bsnes core. I also got a working lsnes directory from a friend but that gave the same error.

![lsnes_error](https://user-images.githubusercontent.com/24705202/28828079-4d3e40ce-76d8-11e7-9bac-da37cfa0270e.PNG)

**Comment by bentley** [comment]
Report it to TASvideos. This is just a crusty old Github fork.
